name: MasterDeployCI
on: [workflow_dispatch]
#   push:
#     branches:
#       - master
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
      - name: Checking out latest code
        uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Packages
        run: npm install

      - name: Deploy to GH Pages
        run: |
          git config --global user.email cmarjun1000@gmail.com
          git config --global user.name cmarjun1000
          git remote set-url origin https://${{secrets.MD_ACCESS_TOKEN}}@github.com/cmarjun1000/md-resume.git
          npm run deploy

      - name: Updating Domain
        run: echo "Update domain"
